### ISSUE TITLE
New post image uploads rotate 90 degrees

### ISSUE THREAD

**Issue by allinfinite** [hometown-fork/hometown#63] opened 2020-05-30 00:33 UTC
### vertical images are rotating -90 degrees. Different angle than in my phone

Hometown 3.1.4
Ruby 2.6.6p146
PostgreSQL 9.6.16
Redis 5.0.7

Brave 1.17 for iOS
iOS 13.5
6s plus

**Comment by ghost** [comment] 2020-06-30 22:57
Hi,

I cannot reproduce this on iOS 13.5.1 with Safari on an iPhone SE (1st gen).
Does this issue still occur?

**Comment by allinfinite** [comment] 2020-07-01 03:25
I just updated and tried.. same issue 🤷‍♂️

**Comment by Packbat** [comment] 2022-06-02 20:07
There's an intermittent issue with at least some iPhones where different parts of the metadata on the image disagree about its orientation in a way that confuses Mastodon and its forks - I'm not sure how to resolve it correctly, but I think I heard the term "EXIF" somewhere?

**Comment by dheadshot** [comment] 2022-11-19 15:51
I've encountered this error (I think) with other web stuff. When you rotate an image on an iPhone it only rotates the view for the image not the image itself, so when displayed by other renderers it's rotated back to the original direction. If the camera app is doing the rotation automatically, there will always be problems...

**Comment by dariusk** [comment] 2022-11-26 16:24
Closing since this is an iPhone issue (and also quite old).

**Closed as completed by dariusk** 2022-11-26 16:24 UTC
Labels: bug, good first issue
