### ISSUE TITLE
Report seemingly vanished.

### ISSUE THREAD

**Issue by reeseovine** [hometown-fork/hometown#1177] opened 2022-07-15 02:24 UTC
### Steps to reproduce the problem

1. A user of our instance reported somebody's post.
2. One of us was able to view the reported post and the user's profile but then...
3. The post and profile suddenly disappeared from our instance.

The report is not in the list in the admin dashboard anymore. The dashboard link that was emailed to us now brings up a 404 page with the message:

> _The page you are looking for isn't here._

Attempting to visit the reported user's profile on their instance brings up a `410 Gone` page which says:

> _The page you were looking for doesn't exist here anymore._

Searching for the user on our instance brings up nothing either.

### Expected behaviour

 Usually when a user is banned the report still stays in our dashboard.

### Actual behaviour

It seems like the user was completely removed from their server in a way that also removed them from ours. Is that even possible?

### Specifications

Mastodon version: `v1.0.5+3.5.2`  
Hometown version: `v1.0.5`

**Comment by ironiridis** [comment] 2022-08-16 20:26
Happened again on the same above-mentioned instance. We had a report indexed as number 325 and it is completely invisible in the moderation interface now. Likewise, the account page on the target instance returns a `410 Gone` indicating maybe they've been banned or removed somehow. This is ... fine, I guess, but it poses a bit of an accountability issue that a target instance can effectively destroy audit logs on our instance.

**Comment by ghost** [comment] 2022-08-17 07:24
Hello all,

I believe it's simply how federated reports work. You'd better take this issue upstream to Mastodon if you want it to be fixed: https://github.com/mastodon/mastodon. 😕

**Comment by johnholdun** [comment] 2022-11-10 02:57
Yeah, this sounds to me like ActivityPub working as intended, for better or worse. If something is deleted—a status, a user, etc.—then that deletion is federated in the same way its creation was. Mastodon (and, by extension, Hometown) is acting in good faith here to remove all references to the deleted thing.

A potential enhancement here would be to preserve the report, even if all the details about the deleted user were redacted—something like "The reported (post/user) no longer exists," as opposed to the report itself disappearing.

**Comment by dariusk** [comment] 2022-11-18 03:54
Yeah @johnholdun is correct. The issue here is definitely Mastodon doing what it's supposed to as a good faith fediverse actor -- if it gets a message from another server that a user was deleted, Mastodon goes out of its way to delete ALL references to that user. I think this is correct behavior, and I also like John's suggestion for a report that doesn't just vanish but remains with a placeholder. It wouldn't have any data about the deleted user though, just an anonymous "this user was deleted by the remote server" etc.

**Comment by dariusk** [comment] 2022-11-18 03:57
Closing now that there is a feature request open at #1204.

**Closed as completed by dariusk** 2022-11-18 03:57 UTC
